In [18]:
import numpy as np
import random
from copy import copy
from matplotlib import pyplot as plt

from simulation_helpers import generateAdjacenyMatrix
from optimal_policy import computeTransY

from heuristics import selectRandom
from heuristics import highRisk
from heuristics import highConnection
from heuristics import highBelief
from heuristics import sampleBelief
from heuristics import highBeliefRisk
from heuristics import sample

In [19]:
n = 10
L = 2
p = 1
q = 0
h = 10

In [20]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(selectRandom, Q, h, p, q, L, A, n)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [21]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(highRisk, Q, h, p, q, L, A, n)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


In [22]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(highConnection, Q, h, p, q, L, A, n)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [23]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(highBelief, Q, h, p, q, L, A, n)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


In [24]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(sampleBelief, Q, h, p, q, L, A, n)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [25]:
A = generateAdjacenyMatrix(n, 1)
Q = np.ones(n).astype(np.bool)
print sample(highBeliefRisk, Q, h, p, q, L, A, n)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [26]:
# plt.plot(a, label = 'rank belief')
# plt.plot(b, label = 'random select')
# plt.plot(c, label = 'effect of the removed')

# plt.legend(loc = "lower right")